### ISSUE TITLE
ERROR: Error: image library/piwik:latest not found

### ISSUE THREAD

**Issue by f0086** [piwik/docker-piwik#12]
docker-compose up stops with the following error:

> [...]
> Status: Downloaded newer image for mysql:latest
> Creating piwik_db_1
> Pulling app (piwik:latest)...
> Pulling repository docker.io/library/piwik
> ERROR: Error: image library/piwik:latest not found

**Comment by kosssi** [comment]
Hello @f0086 You can see https://github.com/piwik/docker-piwik/issues/1 ;)

**Comment by pierreozoux** [comment]
Thanks @kosssi
