### ISSUE TITLE
is it possible to use --link mysql:mysql ?

### ISSUE THREAD

**Issue by shinexia** [piwik/docker-piwik#13]
I have a mysql docker image running already, i want to link to that image, but i don't know how. can you give me some advises? thank you very much!

**Comment by pierreozoux** [comment]
As you can see here: https://github.com/piwik/docker-piwik/blob/master/docker-compose.yml#L9-L10
This is the equivalent to `--link db:mysql` but you can also use `--link mysql:mysql`.

I close the issue, but do not hesitate to reopen if you feel the answer is not complete.
