### ISSUE TITLE
piwik container not found

### ISSUE THREAD

**Issue by zorino** [piwik/docker-piwik#15]
Pulling repository docker.io/library/piwik
ERROR: Error: image library/piwik:latest not found

**Comment by whippersnapper** [comment]
ditto. also getting the same.

**Comment by pierreozoux** [comment]
Yes, the image is not yet official.
In the mean time, you can build it yourself.

I'll let you know once it is official.

On 26-01-2016 08:38, Ling wrote:
> ditto. also getting the same.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/piwik/docker-piwik/issues/15#issuecomment-174890738
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by whippersnapper** [comment]
Ok. Great. Thanks for the quick response @pierreozoux.

**Comment by pierreozoux** [comment]
Now official
