### ISSUE TITLE
Crontab archive issue: Name or service not known

### ISSUE THREAD

**Issue by Toub** [piwik/docker-piwik#17]
Thanks for this good docker configuration.

However, I have some issue with the crontab job.

1) When I try to run the archive command manually (from inside the cron container), I get the following error: 

``` console
root@bfa28b94d1c0:/var/www/html# su www-data -c "/usr/local/bin/php /var/www/html/console core:archive"
This account is currently not available.
```

Cause group www-data does not exists in the container.

2) When I launch the command as root, I have a network error, even if I specify the piwik URL as it is [documented as "required"](http://piwik.org/docs/setup-auto-archiving/).

``` console
root@bfa28b94d1c0:/var/www/html# /usr/local/bin/php /var/www/html/console core:archive --url=http://piwik.mydomain.com                 

  [Zend_Db_Adapter_Exception]                                                                     
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  

  [PDOException]                                                                                  
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  
```

Both piwik.mydomain.com  and piwik.org pings are OK.

Any help appreciated!

**Comment by pierreozoux** [comment]
You can run like this:

```
su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
```

If you cat `/etc/passwd` you'll see that the shell for this user is
nologin, this is what cause the error.

But I didn't like it anyway :/

So I changed it: https://github.com/docker-library/official-images/pull/1203#issuecomment-179923977

**Comment by pierreozoux** [comment]
Ok, I think we can close this.
