### ISSUE TITLE
config.ini.php has not been found or could not be read

### ISSUE THREAD

**Issue by pmayer** [piwik/docker-piwik#19]
If I'm trying to run it, I get the following error (via docker logs):
```
The configuration file {/var/www/html/config/config.ini.php} has not been found or could not be read.
If the file exists, please check that /var/www/html/config/config.ini.php is readable by the user 'www-data'.
```
If I log into the container I can see that the file config.ini.php hasn't been created.
Any idea why this is happening and how it can be fixed?

**Comment by pierreozoux** [comment]
Did you go though the web install?

**Comment by pmayer** [comment]
Not quite sure what you mean.

I'm cloning the git repository, build it with `docker build -t piwik ./docker-piwik` and run it with `docker run --link mysql-piwik:mysql -p 8080:80 --name piwik -d piwik`. mysql-piwik is a mysql docker container already running.

**Comment by pierreozoux** [comment]
Then open your web browser :) and Install piwik, it should do the trick

**Comment by pmayer** [comment]
Unfortunately not - I can't open it in the web browser.

Here's the complete docker logs output:

```
[15-Feb-2016 19:57:32] NOTICE: fpm is running, pid 1
[15-Feb-2016 19:57:32] NOTICE: ready to handle connections
The configuration file {/var/www/html/config/config.ini.php} has not been found or could not be read.
If the file exists, please check that /var/www/html/config/config.ini.php is readable by the user 'www-data'.



                                                    
  [Zend_Db_Adapter_Exception]                       
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    




                                                    
  [PDOException]                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    


core:archive [--url="..."] [--force-all-websites] [--force-all-periods[="..."]] [--force-timeout-for-periods[="..."]] [--skip-idsites[="..."]] [--skip-all-segments] [--force-idsites[="..."]] [--force-periods[="..."]] [--force-date-last-n="..."] [--force-date-range[="..."]] [--force-idsegments="..."] [--concurrent-requests-per-website[="..."]] [--disable-scheduled-tasks] [--accept-invalid-ssl-certificate] [--php-cli-options[="..."]]


[15-Feb-2016 19:57:32] ALERT: oops, unknown child (9) exited with code 1. Please open a bug report (https://bugs.php.net).
```

**Comment by pmayer** [comment]
Ah ok - had a look into the source and I think the README is a bit misleading. There is only fpm running on port 9000 inside the docker volume and I need another one (nginx) as fastcgi-proxy - correct?
If you just have a look at the README it looks like you can connect directly to port 80 of the docker volume.

**Comment by pierreozoux** [comment]
Arf, indeed... Do you have an idea to improve the README?

**Comment by pmayer** [comment]
Well - I would remove this part:

...
For testing purpose, you might want to be able to access the instance from the host without the container's IP, standard port mappings can be used:
```
docker run --link some-mysql:mysql -p 8080:80 -d piwik
```
Then, access it via `http://localhost:8080` or `http://host-ip:8080` in a browser.
...

and add instead some information about fpm running on port 9000 inside the container and the need to fastcgi-proxy to it. You could also change the run example to `docker run --link some-mysql:mysql -p 9000:9000 -d piwik`.
And maybe add an examle with a nginx container and nginx.conf - but actually https://github.com/indiehosters/piwik covers that already.

**Comment by pierreozoux** [comment]
I updated the README, I'd be glad to receive your feedback!

**Comment by pmayer** [comment]
far better - I like it :)
