### ISSUE TITLE
TravisCI

### ISSUE THREAD

**Issue by pierreozoux** [piwik/docker-piwik#2]
we could also enable Travis CI for this repository. On each commit, a build is triggered. The build is basically a VM and you can execute anything you want, eg. to run some tests, build some package, etc.

**Comment by mattab** [comment]
Hi @pierreozoux 
Shall I enable Travis CI for the repository? just let me know

**Comment by pierreozoux** [comment]
Yes, I added travis.yml, can you activate please? (I'm curious, it'll be my first travis project :) )

**Comment by mattab** [comment]
Hi Pierre, Travis CI is now enabled for the repo!

**Comment by pierreozoux** [comment]
Can you point the link? (I'm missing it)

On 12-11-2015 01:16, Matthieu Aubry wrote:
> Hi Pierre, Travis CI is now enabled for the repo!
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/piwik/docker-piwik/issues/2#issuecomment-155966416
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by mattab** [comment]
Added icon to the README, we needed to trigger a build and had idea in the same minute ;-) https://github.com/piwik/docker-piwik#piwik

**Comment by pierreozoux** [comment]
ok, looks like it is on the way :)

**Comment by pierreozoux** [comment]
\o/
