### ISSUE TITLE
Make readme more clear

### ISSUE THREAD

**Issue by ponychicken** [piwik/docker-piwik#20]
Right now the getting started is not understandable without docker experience:

* What is some-mysql? Mention that you need a mysql instance running, recommend a popular option
* Do I need to pull it from somewhere? Do I need to get the git repo? Or where does the data come from? Running the `docker run` command on a fresh machine seems to do nothing
* How does the port mapping work, which one is the internal, which one the external?
* Does the docker stuff restarts after a reboot, or what do I need to do for it to be like this?

**Comment by pierreozoux** [comment]
On 25-02-2016 11:42, Leo Koppelkamm wrote:
> 
> * What is some-mysql? Mention that you need a mysql instance running, recommend a popular option
This is the standard description for a lamp image. Check
[WordPress README](https://hub.docker.com/_/wordpress/)

> * Do I need to pull it from somewhere? Do I need to get the git repo? Or where does the data come from? Running the docker run command on a fresh machine seems to do nothing
It is about to get official. In the meantime: `docker build` is your
friend :)

> * How does the port mapping work, which one is the internal, which one the external?
I updated the README, is it clearer now?

> * Does the docker stuff restarts after a reboot, or what do I need to do for it to be like this?
I believe this is more a question about docker in general, and not
really related to piwik.

But if you have suggestions, we are happy to accept PR.

> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/piwik/docker-piwik/issues/20
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux
