### ISSUE TITLE
piwik website not accessible

### ISSUE THREAD

**Issue by keltik85** [piwik/docker-piwik#22]
I have created a mysql image using a `Dockerfile` like so:

```
FROM mysql:latest
```
and then builded it with this command: `docker build -t someMysql .`

After that i have created a `Dockerfile` for the piwik image like this:

```
FROM piwik:latest
```

and builded it with this command: `docker build -t somePiwik .`

when I do `docker images` I can see this:
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
somePiwik        latest              8c35c3d8471f        About an hour ago   551 MB
someMysql        latest              4c8234833e34        4 hours ago         361.2 MB
mysql               latest              7a5866c2edbf        7 days ago          361.2 MB
piwik               latest              b51d068b5d69        13 days ago         551 MB
```

Then i run the image for mysql like this:
`docker run --name mysqlcontainer -e MYSQL_ROOT_PASSWORD=root -d someMysql:latest`
And also the piwik image like this linking it with the appropriate argument to the mysql-docker-container:
`docker run --name piwikcontainer --link mysqlcontainer:mysql -p 9001:9000 -d somePiwik:latest`

When I do a `docker ps` i see the following:
```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                    NAMES
86a5a84ce311        somePiwik:latest      "/entrypoint.sh php-f"   23 minutes ago      Up 23 minutes       0.0.0.0:9001->9000/tcp   piwikcontainer
979ba9fbc19c        someMysql:latest      "/entrypoint.sh mysql"   About an hour ago   Up About an hour    3306/tcp                 mysqlcontainer
```
It seems like everything is mapped fine.

According to the [Piwik-site](https://hub.docker.com/_/piwik/) I should be able to use my ** browser** to  browse the **piwik login-page** using `http://localhost:9001` .

Unfortunately this is not working, as I get the follwoing error from my `lynx` browser:
```
[root@localhost mysql]#  lynx http://localhost:9001
Looking up localhost:9001
Making HTTP connection to localhost:9001
Sending HTTP request.
HTTP request sent; waiting for response.
Alert!: Unexpected network read error; connection aborted.
Can't Access `http://localhost:9001/'
Alert!: Unable to access document.
lynx: Can't access startfile
```

**1. What am I doing wrong?**
**2. Have I misunderstood the [Piwik-site](https://hub.docker.com/_/piwik/) ?**
**3. Can someone help me to get going?**

**Comment by sebastienvermeille** [comment]
Same here ... can't figure out why

**Comment by matt-hh** [comment]
Hi, 

see "How to use this image" at https://hub.docker.com/_/piwik/

"Now you can get access to fpm running on port 9000 inside the container." means:
You can set up a web server like nginx and access port 9000 inside the web server configuration.

Php-fpm is a fastcgi server and not a http server. You have no direct access via curl/lynx.

Look at these two files from "docker-compose" section:

https://github.com/indiehosters/piwik/blob/master/docker-compose.yml
- app is the piwik php-fpm process at port 9000
- web ist the nginx server
- web uses volume from app (/var/www/html/)
- web uses the following nginx.conf (line 18)

https://github.com/indiehosters/piwik/blob/master/nginx.conf
- upstream to web:9000
- config to handle .php-files see line 38-58
- root /var/www/html/ (line 20) is the volume from app container

Hope this helps you...

**Comment by sebastienvermeille** [comment]
@matt-hh aha ok... well I would need an "all in one" solution with an external db container.

I am not enough famiiar with docker images for now I will do it later. Thank you for your answer :)

**Comment by pierreozoux** [comment]
Thanks @matt-hh for your deep answer.
It is indeed difficult in the docker hub to explain how to make it running with php-fpm.
Maybe a way would be to use apache...

Anyway, if you have any suggestions on how to improve the README, would be amazing :) (suggestion means PR ;)
