### ISSUE TITLE
How to access piwik from outside the server?

### ISSUE THREAD

**Issue by Algram** [piwik/docker-piwik#25]
The readme states I need a reverse proxy and so I tried the docker-compose option with the indiehosters-repo. I ran into multiple issues and couldn't resolve those.

I would much rather have some "official" information on this repo on how to accomplish what I want.
At the moment it seems kind of foggy and it would be great to get some input on that.

Thanks!

**Comment by pierreozoux** [comment]
Hey! IndieHosters repo and this image is the same person: me :)

If it is not exactly clear, I'm really sorry, but I lack a bit of time lately :/ Please ask your questions on indiehosters repo about anything regarding docker-compose. I'll try to answer in a timely manner.

(sorry)
