### ISSUE TITLE
problem to run docker

### ISSUE THREAD

**Issue by miira** [piwik/docker-piwik#27]
Hello,
I installed DockerToolBox (win), cloned docker-piwik repository and tried to run docker:

$docker-piwik> docker run --link mysql:db -d piwik
docker: An error occurred trying to connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.23/containers/create: open //
./pipe/docker_engine: The system cannot find the file specified..
See 'docker run --help'.

I also tried to setup proxy, but without any change in the message.

Do you have any idea, what could be wrong?
Thank you

**Comment by pierreozoux** [comment]
Looks like an issue with your docker instance.
Can you run the hello world container?
`docker run hello-world`

Once you got that fixed, you can reopen here :)

**Comment by miira** [comment]
I cannot run the hello world container, it writes the very same message. 
How can I fix that? The steps so far were just installation and clone of repository. Is there some configuration files somewhere? The only non-standard thing I did, was that I installed DockerToolBox to path WITHOUT spaces (non-default), but that should help, not make it worse, I guess. :) 

I'm not reopening it, because I cannot fix it. I hope you can help me anyway....
Thank you

**Comment by miira** [comment]
probably I should reopen it, otherwise it won't catch eyes. sorry for not following your instructions.

**Comment by miira** [comment]
I would like to reopen the issue, it seems, I won't get reply otherwise. But here is no button to reopen it... :/

**Comment by pierreozoux** [comment]
The issue is not related to piwik, I'm sorry, please go to docker forum to find help to solve your issue.
https://www.docker.com/docker-support-services
