### ISSUE TITLE
Container does not Respond Any Data

### ISSUE THREAD

**Issue by vanthome** [piwik/docker-piwik#29]
I'm running this image on a docker 1.11.0 host like this:

```
docker run --name piwik -d -p 8002:9000 -e MYSQL_ROOT_PASSWORD=pw --link piwik_mdb:db piwik:2.16.0
```
Of course the mariadb container is running as well.
I cannot seem to get a response from the container although the port is open.
Even if I shell into the container, a curl looks like this:

```
root@ccfcbb9aac9a:/var/www/html# curl http://localhost:9000
curl: (56) Recv failure: Connection reset by peer
```

**Comment by pierreozoux** [comment]
We expose an fpm process, so I doubt you curl into it.
But you should put a web server in front!
There is a setup with nginx and docker-compose here: indiehosters/piwik

Let me know if you have issues!

Pierre

On 21-05-2016 14:11, Thomas Hoppe wrote:
> I'm running this image on a docker 1.11.0 host like this:
> 
> |docker run --name piwik -d -p 8002:9000 -e MYSQL_ROOT_PASSWORD=pw --link
> piwik_mdb:db piwik:2.16.0 |
> 
> Of course the mariadb container is running as well.
> I cannot seem to get a response from the container although the port is
> open.
> Even if I shell into the container, a curl looks like this:
> 
> |root@ccfcbb9aac9a:/var/www/html# curl http://localhost:9000 curl: (56)
> Recv failure: Connection reset by peer |
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/piwik/docker-piwik/issues/29>
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by vanthome** [comment]
I don't think that I need a web server just to test the functionality and that's all I want to do (production is a different issue). Also I tried with a browser from outside the container (Port 8002 in this case); again: it simply does not work. You might want to try it. It might be an issue with recent docker versions. I remember a different project that had problems with it.

**Comment by pierreozoux** [comment]
I'm sorry, fpm doesn't speak http, so you need a web server in front.
Let me know if you have question on how to do so, but besides that, I can't help you.
(I close as the documentation is already explicit about it)

But I agree with you, we could have an apache version that would work out of the box. If you want to PR, you are more than welcome :)

**Comment by vanthome** [comment]
Oh, ok, I wasn't aware of that! I thought fpm would do http as well.
Many thanks then!
