### ISSUE TITLE
Piwik returns a blank page

### ISSUE THREAD

**Issue by guiniol** [piwik/docker-piwik#30]
Hello,

So, I'm probably doing something wrong, but the best I have managed to receive from piwik is a blank page.

I have 3 containers:
- mariadb
- piwik, linked to mariadb
- nginx, linked to piwik

Depending on my nginx configuration, I either get a "File not found." (not a 404, a literal string) which I interpret as nginx not passing the right cgi parameters, or a blank page. For me the blank page indicates that nginx talks to piwik, finds, the php script, but then the php fails to execute properly. I used the configuration from here too: https://github.com/perusio/piwik-nginx with the same results.

I tried running a shell inside the piwik container, and when I launch `php index.php` or `php piwik.php`, I get the following error:

```
Uncaught exception: The configuration file {/var/www/html/config/config.ini.php} has not been found or could not be read.
If the file exists, please check that /var/www/html/config/config.ini.php is readable by the user 'www-data'.
in /var/www/html/core/Application/Kernel/EnvironmentValidator.php line 63
#0 /var/www/html/core/Application/Kernel/EnvironmentValidator.php(44): Piwik\Application\Kernel\EnvironmentValidator->checkConfigFileExists('/var/www/html/c...', false)
#1 /var/www/html/core/Application/Environment.php(185): Piwik\Application\Kernel\EnvironmentValidator->validate()
#2 /var/www/html/core/Application/Environment.php(94): Piwik\Application\Environment->validateEnvironment()
#3 /var/www/html/core/dispatch.php(28): Piwik\Application\Environment->init()
#4 /var/www/html/index.php(27): require_once('/var/www/html/c...')
#5 {main}
```

I would imagine the `config.ini.php` gets created the first time piwik is used, but here I am.

So, questions:
- For the first setup, do I point the browser to `index.php`, `piwik.php` or somewhere else?
- Did I miss a configuration step?
- What can I do?

Cheers,

**Comment by guiniol** [comment]
I added `fastcgi_intercept_errors on` to the nginx conf and `php_flag[display_errors] = on` to php-fpm, and I still get a blank page, so I have no idea what is going on...
If anyone has a working installation, I would appreciate the docker commandline and whatever conf files are necessary (only for the piwik container).

**Comment by pierreozoux** [comment]
Hi!

I have a working installation here: https://github.com/indiehosters/piwik

Indeed, after the first start, you have to follow the steps in the webUI to create the configuration file. This would be a nice to have but we didn't implemented yet. Feel free to PR :)

I close the issue, as I'm sure it will solve it, but feel free to reopen if necessary.

**Comment by guiniol** [comment]
Hey!

I'll try again with the indiehoster configuration.
The webUI is at `index.php`, right?

**Comment by guiniol** [comment]
Quick question: why do you add

```
volumes_from:
  - app
```
Is it only for the ssmtp configuration, or is `./config:/var/www/html/config` also necessary?

**Comment by pierreozoux** [comment]
On 20-06-2016 09:21, guiniol wrote:
> Quick question: why do you add
> 
> |volumes_from: - app |
I usually do that. It is for nginx to server static assets, but I'm not
sure in the case of piwik it is really helpful

> 
> Is it only for the ssmtp configuration, or is
> |./config:/var/www/html/config| also necessary?
Nginx doesn't need either ssmtp nor config actually

> 
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/piwik/docker-piwik/issues/30#issuecomment-227078589>, or
> mute the thread
> <https://github.com/notifications/unsubscribe/ABxvHSQ1-ETh-oh8fD7ijwvgpOTKhTJYks5qNk2MgaJpZM4I5M8E>.
> 

-- 
I use PGP to protect our privacy, if you want to know more, you can
follow this
https://emailselfdefense.fsf.org/en/

If you have further questions, please do not hesitate to ask.
You can verify my public key here: https://keybase.io/pierreozoux

**Comment by pierreozoux** [comment]
And yes, `index.php` or `/`

**Comment by guiniol** [comment]
> And yes, `index.php` or `/`

Ok, thanks.

> > `volumes_from: - app`
> I usually do that. It is for nginx to server static assets, but I'm not sure in the case of piwik it is really helpful

In this case, it is only `./config:/var/www/html/config`, so I'm not sure there are any static assets to serve.

**Comment by guiniol** [comment]
So...
I finally got it to work. I made two mistakes:
1. I used the `nginx:alpine` version (smaller footprint), but there are stuff missing for piwik.
2. `volumes-from` also includes the implicit volumes, so that `nginx` can find the non php files.

I hope my mistakes can help someone else not waste so much time.

**Comment by ishtiaque06** [comment]
Hello, 

I have been trying to make Matomo work with my existing docker-compose setup with nginx. The issue I'm facing is exactly the same as this but I feel like I'm still missing something from the discussion above. 

My situation's this: my site is currently at `subdomain.example.com` and it works perfectly fine with the current setup. However, I want to direct all requests to `subdomain.example.com/analytics/*` to the Matomo instance that I'm trying to spin up. I have successfully been able to run `docker-compose up` and fire up all the containers properly. However, when I go to `subdomain.example.com/analytics/`, I get a blank page with a literal string "File not found" as this issue talks about. 

Here are the relevant parts of my `nginx.conf` file:

```
upstream backend {
  server matomo:9000;
}

server {
  client_max_body_size 10M;
  server_name *.example.com;

  listen 443 ssl; # managed by Certbot
  ssl_certificate /etc/letsencrypt/live/example.com/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/example.com/privkey.pem; # managed by Certbot
  include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
  ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

  gzip on;
  gzip_types      text/plain application/xml;
  gzip_proxied    no-cache no-store private expired auth;
  gzip_min_length 1000;

  location /analytics/ {
    rewrite /analytics/(.*)$ /$1 break;
    include fastcgi_params;
    fastcgi_pass dibs_matomo;
    fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
    fastcgi_param  SERVER_SOFTWARE    nginx;
    fastcgi_param  QUERY_STRING       $query_string;
    fastcgi_param  REQUEST_METHOD     $request_method;
    fastcgi_param  CONTENT_TYPE       $content_type;
    fastcgi_param  CONTENT_LENGTH     $content_length;
    fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_param  REQUEST_URI        $request_uri;
    fastcgi_param  DOCUMENT_URI       $document_uri;
    fastcgi_param  DOCUMENT_ROOT      $document_root;
    fastcgi_param  SERVER_PROTOCOL    $server_protocol;
    fastcgi_param  REMOTE_ADDR        $remote_addr;
    fastcgi_param  REMOTE_PORT        $remote_port;
    fastcgi_param  SERVER_ADDR        $server_addr;
    fastcgi_param  SERVER_PORT        $server_port;
    fastcgi_param  SERVER_NAME        $server_name;
    fastcgi_intercept_errors on;
    fastcgi_read_timeout 300;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $fastcgi_path_info;
    
}
```

Relevant parts of my docker-compose.yml (some definitions removed for brevity):

```
services:
  nginx:
    image: nginx
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./matomo-config:/var/www/html/config:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - gunicorn
      - certbot
  matomo:
    image: matomo:fpm-alpine
    depends_on:
      - matomo_database
    volumes:
      - ./matomo-config:/var/www/html/config:rw
    expose:
      - 9000
    environment:
      *common-variables

  matomo_database:
    image: yobasystems/alpine-mariadb
    volumes:
      - /data/example/mysql:/var/lib/mysql
    # command: mysqld --innodb-buffer-pool-size=10M
    environment:
      *common-variables
```

I can give more details if necessary. I'm also pasting the logs I get when I make a request to `subdomain.example.com/analytics/`.

```
matomo_1           | 192.168.48.10 -  29/May/2019:12:14:08 +0000 "GET /" 404
nginx_1            | 2019/05/29 12:14:08 [error] 9#9: *1 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 165.82.203.83, server: *.example.com, request: "GET /analytics/ HTTP/1.1", upstream: "fastcgi://192.168.48.6:9000", host: "subdomain.example.com"
nginx_1            | xxx.xxx.xxx.xxx - - [29/May/2019:12:14:08 +0000] "GET /analytics/ HTTP/1.1" 404 47 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

Any help would be much appreciated! 

Thank you.

**Comment by kieste** [comment]
Hi @ishtiaque06, did you solve your issue? Same problem here! Thanx
