### ISSUE TITLE
Using a volume for application code make updates cumbersome

### ISSUE THREAD

**Issue by morvans** [piwik/docker-piwik#34]
The official Docker image for Piwik declares /var/www/html as a Docker volume, in order to expose PHP sources to other containers of the stack, such as a nginx or any other webserver, which will serve as a frontend for static files and relay requests to Piwik container via PHP-FPM.

The issue is that /var/www/html is populated at first startup and as it's a volume, it will be persisted on further container recreate (such as updating piwik to a newer version) : in such case, you want to only change the version number in a docker-compose.yml file, and do a docker-compose pull && docker-compose up -d.

In that case, the old version of piwik will still be served, unless you manually clean up the /var/www/html volume beforehand (and if you hopefully host-mounted it to a know location...).

The only solution I can forsee is to provide another image, based on nginx image, which also has Piwik source, thus eliminating the need of a volume to share it. Another way of solving the issue is to make only one image, based on php:5.6-apache instead of 5.6-fpm and have the webserver included.

This is a recurrent issue of many PHP-based projects (see for example https://github.com/CachetHQ/Docker/issues/106) and as many people tend to prefer nginx+fpm over apache+mod_php, I would suggest that we work with maintainers of the official php image to provide a "-nginx" flavor of the image.

**Comment by pierreozoux** [comment]
I agree with the problem space, but not with the solution space.

We should use the copy technique used by [ownCloud](https://github.com/docker-library/owncloud/blob/master/9.1/fpm/docker-entrypoint.sh#L5) and [WordPress](https://github.com/docker-library/wordpress/blob/master/fpm/docker-entrypoint.sh#L28)

Would you like to submit a PR?

**Comment by morvans** [comment]
As far as I understand, theses two projects do exactly [what piwik is doing](https://github.com/piwik/docker-piwik/blob/master/docker-entrypoint.sh#L5) and do not handle updates either.
It's even mentioned as a [TODO](https://github.com/docker-library/wordpress/blob/master/fpm/docker-entrypoint.sh#L48) for wordpress.

**Comment by pierreozoux** [comment]
Ok, you are right, sorry.

In that case, the update procedure is:

`docker-compose pull && docker-compose stop && docker-compose rm -f && docker-compose up -d`

I always recycle the containers to be sure no state is lying around. Containers should be stateless :)

I use this unit file to manage them:
https://github.com/indiehosters/LibrePaaS/blob/master/unit-files/u%40.service

so in my case, I just go to the dir and `docker-compose pull && restart`

I'll close the issue, but feel free to reopen it if you feel like.

**Comment by morvans** [comment]
Your approach work because you must be mapping all other volumes (esp. mysql data volume) to a specific host directory instead of letting docker managing it. Otherwise, it would also be destroyed by docker-compose rm.
I wonder if this approach is really manageable in multi-host configuration like swarm or kubernetes...

**Comment by pierreozoux** [comment]
Docker is good at solving [12factor](http://12factor.net/). Piwik, like many lamp apps, are from time before 12 factor.

For instance, they (ownCloud or WordPress) use local filesystem to store local data. This is against 12 factor. You should just consume other services (you can tell WordPress or ownCloud to actually consume S3 for instance).

But actually, in the case of piwik, this is fine, it doesn't store state, it just consumes mysql.
So in the specific case of piwik, you should be fine on a multihost approach, as long as you have a mysql service running well. How to do a good mysql service is another debate :)

Piwik is stateless, so everything is good :) 12factor gods should be happy!

**Comment by morvans** [comment]
Couldn't agree more on the 12-factors part, but, still, I find it really "dirty" to share application source code between containers using volumes. And if the nginx container doesn't end up on the same swarm host than fpm container, you'll have to rely on shared storage to make sure everything works. If source code was packaged in two images "piwik-fpm" & "piwik-nginx", you'll be fine.
