### ISSUE TITLE
Impossible access to piwik...

### ISSUE THREAD

**Issue by SuperITMan** [piwik/docker-piwik#36]
Hello,

I'm trying to run piwik on my Docker server but I have some issues.
My Nginx-server is configured as it should (I think) but I get an error 502 when I connect to piwik...
Could you please help me to find a solution to use Piwik with the official Docker image.

Here, different logs.
Piwik logs after : 

> 24-Aug-2016 12:02:16] NOTICE: fpm is running, pid 1
> [24-Aug-2016 12:02:16] NOTICE: ready to handle connections

Command to launch piwik : 

> docker run -it -d --name piwik --link database:db piwik:latest

Nginx configuration : 

> upstream tfe2.ags.ovh {
>                                 ## Can be connect with "bridge" network
>                         # piwik-test
>                         server 172.17.0.8:9000;
> }
> server {
>         server_name tfe2.ags.ovh;
>         listen 80 ;
>         access_log /var/log/nginx/access.log vhost;
>         return 301 https://$host$request_uri;
> }
> server {
>         server_name tfe2.ags.ovh;
>         listen 443 ssl http2 ;
>         access_log /var/log/nginx/access.log vhost;
>         ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
>         ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA;
>         ssl_prefer_server_ciphers on;
>         ssl_session_timeout 5m;
>         ssl_session_cache shared:SSL:50m;
>         ssl_certificate /etc/nginx/certs/tfe2.ags.ovh.crt;
>         ssl_certificate_key /etc/nginx/certs/tfe2.ags.ovh.key;
>         ssl_dhparam /etc/nginx/certs/tfe2.ags.ovh.dhparam.pem;
>         add_header Strict-Transport-Security "max-age=31536000";
>         include /etc/nginx/vhost.d/default;
>         location / {
>                 proxy_pass http://tfe2.ags.ovh;
>         }
> }

Nginx error log : 

> 2016/08/24 12:25:22 [error] 64#64: *58 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: < ip_address >, server: tfe2.ags.ovh, request: "GET / HTTP/1.1", upstream: "http://172.17.0.8:9000/", host: "tfe2.ags.ovh"

Thank you for your time.

**Comment by molecode** [comment]
I have the same problem here. It seems, that you cannot connect directly to port 9000 in the nginx.conf file, because it runs fastcgi/php (I think). Have a look at the nginx.conf file https://github.com/indiehosters/piwik (this is linked from the official piwik docker site). You need to put fastcgi params in the nginx config file. It is working for me here now. But only for php pages, piwik.mydomain.tld/index.php is nearly working, but it cannot find some static content like css/js/img.

**Comment by pierreozoux** [comment]
@SuperITMan did the comment from @molecode helped you resolve your issue?

If not, please feel free to reopen!
