### ISSUE TITLE
External Mysql

### ISSUE THREAD

**Issue by manucho6** [piwik/docker-piwik#37]
Hi everyone,

I would  like to know if there is a possibility to run a piwik container "linked" to an external mysql database server.

I will appreciate your help...

**Comment by TheNotary** [comment]
the docker-piwik container should have network access and therefore, if you supply the database connection info to an external mysql database server during the installation steps when you first boot the container, it should just work.

**Comment by pierreozoux** [comment]
Yes, actually the README explains it well:
https://github.com/piwik/docker-piwik#runtime

Please reopen if you can't manage to make this working!
