### ISSUE TITLE
Unable to access interface

### ISSUE THREAD

**Issue by sjiveson** [piwik/docker-piwik#38]
Hi, 

I'm attempting to use the latest image available on Docker hub.

Myself and a number of colleagues have failed to connect to the web interface to configure the container (via HTTP or HTTPS).

I've used this run command: `sudo docker run -d --name piwik -p 9000:9000 --link piwik-db piwik:latest`.

The `ss-ltn` command on my host lists 9000 as a listening port. The same command in the container lists 9000 as a listening port.

The output of the `docker ps` command shows the NAT is in place:
```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
d108729f910f        piwik:latest        "/entrypoint.sh php-f"   13 minutes ago      Up 13 minutes       0.0.0.0:9000->9000/tcp   piwik
```

Despite all this, when I attempt to connect via port 9000 in a browser I either get an empty response or a connection refused error. 

A tcpdump on the host typically shows the connection is setup, a GET sent and ACK's and then two resets sent by the container. This clearly indicates no iptables or other firewall issues.

Curls performed within the container result in this error (whether using localhost or the container's actual 172. address):

`curl: (56) Recv failure: Connection reset by peer`

**Comment by pierreozoux** [comment]
DId you read carefuly the readme?

https://github.com/piwik/docker-piwik#how-to-use-this-image

Either you didn't read it carefuly enough, or it is not explicit enough, but we have to fix something :)

**Comment by mark-r-m** [comment]
Hello - I am having a similar problem.
We've got this docker compose file, being run in rancher:
```
mysql-db:
  environment:
    MYSQL_ROOT_PASSWORD: Password1
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mysql:latest
  stdin_open: true
piwik:
  ports:
  - 9999:9000/tcp
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: piwik:latest
  links:
  - mysql-db:db
  stdin_open: true
```
My rancher UI reports both containers running properly:
```
Active | mysql-db | Image: mysql:latest |             | Service | 1 Containers |
Active | piwik    | Image: piwik:latest | Ports: 9999 | Service | 1 Containers |
```
The *mysql server* has theselogs:
```8/30/2016 4:03:54 PM Initializing database
8/30/2016 4:03:57 PM Database initialized
8/30/2016 4:03:57 PM MySQL init process in progress...
8/30/2016 4:03:58 PM Warning: Unable to load '/usr/share/zoneinfo/Factory' as time zone. Skipping it.
8/30/2016 4:03:58 PM Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
8/30/2016 4:03:58 PM Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
8/30/2016 4:03:59 PM Warning: Unable to load '/usr/share/zoneinfo/posix/Factory' as time zone. Skipping it.
8/30/2016 4:04:00 PM Warning: Unable to load '/usr/share/zoneinfo/right/Factory' as time zone. Skipping it.
8/30/2016 4:04:00 PM Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
8/30/2016 4:04:00 PM
8/30/2016 4:04:01 PM MySQL init process done. Ready for start up.
8/30/2016 4:04:01 PM```
The *piwik server* has these logs:
```8/30/2016 4:06:52 PM[30-Aug-2016 15:06:52] NOTICE: fpm is running, pid 1
8/30/2016 4:06:52 PM[30-Aug-2016 15:06:52] NOTICE: ready to handle connections```

However, when I browse to the `IP:port` of my host VM, like this: 
*http://192.168.99.252:9999/*
I get the following error:
`ERR_CONNECTION_RESET: The connection was reset`

...can you please advise?

Following the instructions on the page https://github.com/piwik/docker-piwik just says
> 'docker run --link some-mysql:db -d piwik' 
and 
> Now you can get access to fpm running on port 9000 inside the container.
 ...which is very much what we have done.

Please help :-)

**Comment by sjiveson** [comment]
Hey @pierreozoux, there's unfortunately not much to read and I've detailed my run command which doesn't appear to be missing anything.

I assume I'm correct in attempting to connect over HTTP?

I'm happy to provide whatever information you need to assist you.

**Comment by mattab** [comment]
Hi guys, it seems something is not clear to users and we should try to think how to make it clear to everyone. For example it could be just adding few sentences to the readme so people know what to expect the limitations of the project if any. 

In the past there were several issues reported that seem similar to this one: https://github.com/piwik/docker-piwik/issues/31 https://github.com/piwik/docker-piwik/issues/25  https://github.com/piwik/docker-piwik/issues/22#issuecomment-201944691 - it seems people get confused with connecting over HTTP while the container does not support it... I don't know how to solve this issue but i'm sure one of you will do so cheers.

**Comment by sjiveson** [comment]
Ah, I see now. I didn't pick up on that at all although I did wonder why there was no mention of a browser or URL. 

I'd be happy to have a stab at improving the readme later today.

**Comment by mark-r-m** [comment]
Hi folks.
The readme example needs to have the 3 example containers you need - *all* of `mysql`, `piwik`, and `nginx`

So - it would *really really* help if the readme specified these points:
From
> https://github.com/piwik/docker-piwik/issues/31
> By *[TheNotary](https://github.com/TheNotary)*
> ..fpm communicates via the fast CGI protocol rather than via http. Nginx can be used to translate fastCGI to http via the fastcgi_pass directive so browsers can speak communicate with it
> ...this container only contains the FPM service, and therefore can't be used out of the box because it relies on mysql, an http proxy, and also an email service
And from
> https://github.com/piwik/docker-piwik/issues/22#issuecomment-201944691
> By *[matt-hh](https://github.com/matt-hh)*
> You can set up a web server like nginx and access port 9000 inside the web server configuration.
> Php-fpm is a fastcgi server and not a http server. You have no direct access via curl/lynx.

**Comment by pierreozoux** [comment]
@mark-r-m could you make a PR please?

Thanks!

**Comment by sjiveson** [comment]
I've raised https://github.com/piwik/docker-piwik/pull/39. It's not perfect but a major improvement.
