### ISSUE TITLE
Effort to make more accessible/ deployable

### ISSUE THREAD

**Issue by TheNotary** [piwik/docker-piwik#42]
After some time playing around with the piwik deployment code out there, I decided this repo would be best to work off of, but I did notice some rough corners.  
1. Configuration of the app couldn't be automated
2. All commands required to boot the app were not documented or tracked into the repo (relates to #31)
3. There's no 'quick' deploying

For my needs, I built a [repo](https://github.com/TheNotary/piwik-dokku) that could be deployed directly to dokku (the diy heroku).  Piwik was first created long before the concenpt of 12f, honestly it's a bit of a miracle that it's capable of operating in linux containers (and only thanks to the volume management systems).  To allow for a deploy that could be configured once and in a configuration file, I setup the container to configure Piwiks on-file-system config file to accept "API" requests that finished the configuration steps.  I only went as far as configuring up to the point of the website setup, but others might want to be able to fully configure the app.  This sufficed rough corner 1 for me, and the scripts related to the work can be seen [here](https://github.com/TheNotary/piwik-dokku/tree/master/automated_piwik_configs).  Though I should point out, I'm still disappointed with these automation scripts because they didn't work on Heroku.  

To solve problem to for my own needs, I wrote a Makefile that contained the commands needed to bring the container fully online.  You can see a [Makefile](https://github.com/TheNotary/piwik-dokku/blob/master/Makefile) that suffices the criteria.  So when I wanted to test to see that the repo was still working I typed `make` to build the docker container, followed by `make boot-containers-dependency` which only booted a MySQL container.  This is because I included steps to boot an nginx server within the dockerfile.  I did this partly because I didn't off-hand know what command could be used to boot an nginx service in a seperate container and partly to suffice rough corner 3

Finally, to make deploying piwik quick and snappy, I added some dokku/ heroku files to allow the repo to be pushed directly to a PaaS service (dokku) to complete the majority of the installation other than Piwik's firstWebsiteSetup action.  This approach to configuring Piwik relates closely to #41

That all being said, who here want's...
- A Makefile containing commands for bringing up the app?
- Nginx to be included in the Dockerfile?
- Dokku friendly modifications?
- An On-Deploy script that automates the setup of Piwik so it can be configured via a configuration file?

**Comment by Finkes** [comment]
I agree, there sould be an easier way to get piwik up and running without having to setup a webserver. Maybe there could be one version with and one without a webserver included.

**Comment by pierreozoux** [comment]
Yes, the way to go would be to have an apache version.

I close this in favor of #47.

If anybody is willing to PR to add this apache, would be awesome :)
