### ISSUE TITLE
latest tag not pointing to newest release

### ISSUE THREAD

**Issue by heinemml** [piwik/docker-piwik#43]
Hi,

the latest Tag is still pointing to 2.16.2 and not to 2.16.5

```
docker images | grep piwik
piwik                                    2.16                53d13717595a        4 days ago          445 MB
piwik                                    2.16.5              53d13717595a        4 days ago          445 MB
piwik                                    latest              d60109b0993a        2 weeks ago         448.7 MB
```

someone else also mentioned this on hub: https://hub.docker.com/_/piwik/

**Comment by pierreozoux** [comment]
cc @tianon

**Comment by mattab** [comment]
maybe it would be possible to automate the release of new docker-piwik versions? When we release Piwik we run the script here: https://github.com/piwik/piwik-package/blob/master/scripts/build-package.sh - so if we could add some code in there to trigger a new version, maybe worth considering :+1:

**Comment by pierreozoux** [comment]
It is already automated by docker team.

They run [`update.sh`](https://github.com/piwik/docker-piwik/blob/master/update.sh) regularly.

And the latest commit is the result of this automated process.
We already faced this issue.

@heinemml I just tried, and it is fine.
Can you check again please?
If `docker pull piwik` doesn't work, can you try `docker pull piwik:latest`?

**Comment by heinemml** [comment]
Seems to be fixed by now. Strange that it took multiple days 😳

**Comment by tianon** [comment]
Yeah, sorry for the delay -- there's an automated signing system between
our pushes and the tags there, and occasionally it has a hiccup (so thanks
for pointing it out!)
