### ISSUE TITLE
add python to apt-get installs to allow logs import in Piwik

### ISSUE THREAD

**Issue by juliencarnot** [piwik/docker-piwik#46]
The [import logs script](http://piwik.org/log-analytics/) requires python to run. Not sure is this feature should be working out of the box or if it is considered less used and requires a custom dockerfile to python...

**Comment by pierreozoux** [comment]
Let's keep this image small.
But if you can base your image from this one.

Once you have a working image, would be interesting to link to your work then :)

**Comment by psi-4ward** [comment]
Hmm its just 17MB for python... I think the official image should be full functional.

**Comment by juliencarnot** [comment]
@pierreozoux sorry for not linking this before, but I confirm that [apt-get installing python --no-install-recommends](https://github.com/oqpio/docker-piwik/blob/oqplive/Dockerfile) works well.
