### ISSUE TITLE
apache version

### ISSUE THREAD

**Issue by pierreozoux** [piwik/docker-piwik#47]

**Comment by michaelze** [comment]
If nobody has picked this up, I can to provide a PR for this issue.

**Comment by pierreozoux** [comment]
@michaelze Yes, it would be nice :) For that, you'd need to create a folder and add this folder to the script.

The best would be to copy [WordPress](https://github.com/docker-library/wordpress) or [ownCLoud](https://github.com/docker-library/owncloud).

**Comment by SonOfBytes** [comment]
This would be really useful to not have cross mounted containers when trying to run with zero down time rolling upgrades :) How close is this to be completed so we don't roll our own?

**Comment by michaelze** [comment]
I just updated my PR to include the latest request from @pierreozoux.
Should be good to go :).

**Comment by SonOfBytes** [comment]
That's awesome - thank you!

**Comment by SonOfBytes** [comment]
@pierreozoux we are looking to implement apache support ourselves and the attached PR (https://github.com/piwik/docker-piwik/pull/52) would be great to avoid us having to roll our own.  Anything we can do to avoid duplication of effort would be great :)  What kind of timeline would be reasonable to expect for merging the PR?  Are there any issues with this that we can assist with to move this forward?

**Comment by pierreozoux** [comment]
@SonOfBytes sorry, I don't have much time at the moment, and I'm really sorry to be the bottleneck here...

I added some comments to be addressed, and then if you could test things and confirm it is working, I'd merge the work.

Thanks for your patience all, and if anybody wants to step in to help, I'd be grateful!

**Comment by SonOfBytes** [comment]
No worries!

As soon as we have your comments in the PR addressed - I'll see what I can do to test with our current work.

**Comment by michaelze** [comment]
@SonOfBytes I addressed @pierreozoux 's comments so if you like, you can test the setup from my pull request.

**Comment by almereyda** [comment]
I guess this issue can be closed now?

**Comment by tianon** [comment]
Indeed!  Fixed as of https://github.com/piwik/docker-piwik/pull/52. :+1:
