### ISSUE TITLE
3.0.1 missing from Docker Hub

### ISSUE THREAD

**Issue by ginkel** [piwik/docker-piwik#51]
Hi,

would it be possible to publish Piwik 3.0.1 on Docker Hub? ATM, https://hub.docker.com/_/piwik/ still lists 3.0.0 as the current version.

Thanks,
Thilo

**Comment by pierreozoux** [comment]
It is updated here, but I wonder why not on the hub.

ping @tianon

**Comment by webwurst** [comment]
Seems to be fixed: https://hub.docker.com/r/library/piwik/tags/
