### ISSUE TITLE
Assets can't be loaded / 404 for js, css and images / 403 for root url

### ISSUE THREAD

**Issue by henvo** [piwik/docker-piwik#54]
Hey

I am running the latest docker image of piwik with a linked mariadb container:

`docker run --name piwik -d -v /var/www/piwik.example.org/config:/var/www/html/config --link mariadb:db -p 9000:9000 piwik`

The web server is nginx:

```
server {
  listen 443 ssl;
  server_name example.org;

  # SSL related stuff omitted

  root /var/www/html;
  index index.php index.html index.htm;

  location / {
    try_files $uri $uri/ =404;
  }

  error_page 404 /404.html;
  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }

  location = /favicon.ico {
    log_not_found off;
    access_log off;
  }

  location ~ \.php$ {
    fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
    fastcgi_param  SERVER_SOFTWARE    nginx;
    fastcgi_param  QUERY_STRING       $query_string;
    fastcgi_param  REQUEST_METHOD     $request_method;
    fastcgi_param  CONTENT_TYPE       $content_type;
    fastcgi_param  CONTENT_LENGTH     $content_length;
    fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_param  REQUEST_URI        $request_uri;
    fastcgi_param  DOCUMENT_URI       $document_uri;
    fastcgi_param  DOCUMENT_ROOT      $document_root;
    fastcgi_param  SERVER_PROTOCOL    $server_protocol;
    fastcgi_param  REMOTE_ADDR        $remote_addr;
    fastcgi_param  REMOTE_PORT        $remote_port;
    fastcgi_param  SERVER_ADDR        $server_addr;
    fastcgi_param  SERVER_PORT        $server_port;
    fastcgi_param  SERVER_NAME        $server_name;
    fastcgi_intercept_errors on;
    fastcgi_pass backend;
  }
}
```

Although the app is running and I was able to install piwik successfully, it gives me a bunch of 404's for basically all assets like javascript, css and image files:

```
jquery.smartbanner.js?cb=7edb6f9fe6f59cf38a3b442f99b15812
jquery.smartbanner.css?cb=091b6dc35d0c304112383347fa4378f7
logo.svg
loading-blue.gif
jquery.placeholder.js?cb=7edb6f9fe6f59cf38a3b442f99b15812
...
```

Additionally I am not able to access the app via `https://piwik.example.org/`. Instead I **must** enter this URL: `https://piwik.example.org/index.php`. Otherwise this error occurs in the logs:

`[error] 5812#5812: *17 directory index of "/var/www/html/" is forbidden`

What's happening here? And how can I fix this behaviour?

**Comment by pierreozoux** [comment]
Hello!

Please take a look at https://github.com/indiehosters/piwik you should find answers to your questions :)

**Comment by gdelmas** [comment]
@pierreozoux can you please explain where the answers to the question are in the indiehosters repo?

from what i see only php requests are "proxied" via fastcgi. it looks like static image files, js & fonts are not proxied through.
