### ISSUE TITLE
docker-compose up error : library/piwik:latest not found. 

### ISSUE THREAD

**Issue by nawazdhandala** [piwik/docker-piwik#7]

**Comment by pierreozoux** [comment]
Hi, we first need to make this image official.
(we are really close to do so)

In the mean time, you can follow instructions from #1 !

Danke!

Pierre

I'll close when the image will be published.

**Comment by nawazdhandala** [comment]
Sure, Please let me know when you have official image up.

**Comment by nawazdhandala** [comment]
Any updates on this @pierreozoux?

**Comment by pierreozoux** [comment]
Arf sorry, I just PR the official repo \o/

**Comment by nawazdhandala** [comment]
Worked! Thank you so much.
