### ISSUE TITLE
missing 3.1.1 image on docker hub

### ISSUE THREAD

**Issue by gimler** [piwik/docker-piwik#70]
no 3.1.1 image on docker hub see https://hub.docker.com/r/library/piwik/tags/

console error
```
Pulling app (piwik:3.1.1-fpm)...
ERROR: manifest for piwik:3.1.1-fpm not found
```

**Comment by tianon** [comment]
See also docker-library/rabbitmq#188, docker-library/ruby#159, c0b/docker-erlang-otp#75, and docker-library/official-images#3472, https://github.com/docker-library/wordpress/issues/239.


Also, docker-library/oi-janky-groovy@b639001 which should help with this problem in the future.

I've now manually triggered a build of `amd64/piwik` in the meantime.

**Comment by tianon** [comment]
Should be up now!

**Comment by tianon** [comment]
I've filed https://github.com/docker-library/official-images/issues/3835 in order to have a central place to track this problem globally more directly. :+1: :heart:
