### ISSUE TITLE
Install phpredis extension

### ISSUE THREAD

**Issue by evanp** [piwik/docker-piwik#71]
The phpredis extension needs to be installed in order to enable Redis caching.

It seems like there are at least three ways to do it: through apt, through docker-php-ext-install, and with pecl. I don't know what's preferred.

**Comment by sbaerlocher** [comment]
I think this is a good idea. I made a conatiner myself with phpredis support. If interested I would do a PR with phredis support.

What do the maintainers say? @tianon @pierreozoux

**Comment by pierreozoux** [comment]
@sbaerlocher Yes, please do :) Redis is always good to have it!

**Comment by tianon** [comment]
Fixed via https://github.com/piwik/docker-piwik/pull/75. :+1:
