### ISSUE TITLE
Use Piwik with docker ,all visitor ip is same(172.17.0.1)

### ISSUE THREAD

**Issue by Shirakiina** [piwik/docker-piwik#73]
That when I use Piwik with Docker,All visitor show the same IP as 172.17.0.1 ,that is my docker's IP,How can i fix it.
thx

**Comment by Shirakiina** [comment]
resolve it by add this to config.php.ini
proxy_client_headers[] = HTTP_X_FORWARDED_FOR
proxy_host_headers[] = HTTP_X_FORWARDED_HOST

**Comment by agrrh** [comment]
Is it possible to re-open the issue to let developers update the image?
