### ISSUE TITLE
Dockerfile should use EXPOSE for ports

### ISSUE THREAD

**Issue by jouve** [piwik/docker-piwik#74]
Hi,

it would be nice if the Dockerfile used EXPOSE:

- apache: EXPOSE 80
- fpm: EXPOSE 9000

It makes it easy when using the image for the time.

What do you think ?

**Comment by pierreozoux** [comment]
@jouve Yo! Ça roule depuis Evry? :P

Why would you need it?
This is just a metadata. Not much API consumes it actually.

Let me know :)

**Comment by tianon** [comment]
Additionally, those should already be inherited from the `php:apache` and `php:fpm` base image variants, right?

```console
$ docker inspect -f '{{ json .Config.ExposedPorts }}' piwik:apache
{"80/tcp":{}}

$ docker inspect -f '{{ json .Config.ExposedPorts }}' piwik:fpm
{"9000/tcp":{}}
```

**Comment by jouve** [comment]
ca roule ! 

Most of the time, I just ctrl+f the Dockerfile to find which port are exposed but @tianon suggestion is better.
