### ISSUE TITLE
Can't be deployed to IBM Bluemix

### ISSUE THREAD

**Issue by melo0187** [piwik/docker-piwik#8]
Hey there,

TL;DR: Official image can not run out of the box on IBM Bluemix.

Since the image was not up on docker hub, I build it myself locally and ran docker-composer up, which worked just fine. I then went ahead and pushed this image to my private repository on IBM Bluemix so I could start containers on Bluemix based on this image. However, the vulnerability scan fails for the image and thus Bluemix does not allow me to run a container based on this image.

Here are the results of the scan:
1 vulnerable package found:
[DSA-3386-2](https://lists.debian.org/debian-security-announce/2015/msg00298.html)	unzip		Upgrade unzip to at least version 6.0-16+deb8u2

1 policy violation found:
Password lenght not compliant: "Update /etc/login.defs to ensure that PASS_MIN_LEN is >= 8"

**Comment by pierreozoux** [comment]
Hi,

thanks for your report.
I don't think it is our responsability.

This image is based on [php-fpm](https://github.com/docker-library/php/blob/master/5.6/Dockerfile), based on [debian](https://github.com/tianon/docker-brew-debian/blob/d8d023e100f72982b31a8c932570080c3101b7e7/jessie/Dockerfile). I believe all images based on debian will not run on IBM Blemix, so it should be fixed at the debian level.

I'll let you open the issue with them and close this one.

(If you think what I'm saying is wrong, please do not hesitate to reopen it :) )

Thanks!
