### ISSUE TITLE
BUG in web container

### ISSUE THREAD

**Issue by kosssi** [piwik/docker-piwik#9]
Hello,
When I launch `docker-compose up -d` I have this error:

    $ docker-compose up -d
    dockerpiwik_db_1 is up-to-date
    dockerpiwik_app_1 is up-to-date
    Starting dockerpiwik_web_1...
    Cannot start container d72ee0f888c151792036cfecd34f1825f9d829836fb6b94f3e813aa845a2a861: [8] System error: not a directory

You have the same ?

**Comment by pierreozoux** [comment]
How do you start docker? Is it on your linux or though a VM? On my linux, everything is ok.
(There is something wrong, and we should fix it, if not, we'll keep receiving this kind of feedback)

I think you have the same issue as @bmoo here https://github.com/piwik/docker-piwik/issues/1#issuecomment-144619035

**Comment by kosssi** [comment]
My version of docker : 

    $ docker --version
    Docker version 1.9.1, build a34a1d5
    $ docker-compose --version
    docker-compose version: 1.4.1
    $ docker-machine --version
    docker-machine version 0.5.0 (04cfa58)

I test it in virtualbox and digitalocean. I have the same error : 

    $ docker-machine create --driver=virtualbox piwik-dev
    $ eval $(docker-machine env piwik-dev)
    $ docker build -t piwik .
    $ docker-compose up -d

    $ docker-machine create --driver digitalocean --digitalocean-access-token=$TOKEN --digitalocean-region=ams2 piwik-prod
    $ eval $(docker-machine env piwik-prod)
    $ docker build -t piwik .
    $ docker-compose up -d

if I'm connected in the docker-machine : 

    $ docker-machine ssh piwik-dev
    $ docker start -a dockerpiwik_web_1
    Timestamp: 2015-11-26 09:18:59.643291159 +0000 UTC
    Code: System error
    
    Message: not a directory
    
    Frames:
    ---
    0: setupRootfs
    Package: github.com/opencontainers/runc/libcontainer
    File: rootfs_linux.go@40
    ---
    1: Init
    Package: github.com/opencontainers/runc/libcontainer.(*linuxStandardInit)
    File: standard_init_linux.go@57
    ---
    2: StartInitialization
    Package: github.com/opencontainers/runc/libcontainer.(*LinuxFactory)
    File: factory_linux.go@242
    ---
    3: initializer
    Package: github.com/docker/docker/daemon/execdriver/native
    File: init.go@35
    ---
    4: Init
    Package: github.com/docker/docker/pkg/reexec
    File: reexec.go@26
    ---
    5: main
    Package: main
    File: docker.go@18
    ---
    6: main
    Package: runtime
    File: proc.go@63
    ---
    7: goexit
    Package: runtime
    File: asm_amd64.s@2232
    Error response from daemon: Cannot start container dockerpiwik_web_1: [8] System error: not a directory

**Comment by pierreozoux** [comment]
Did you try to ssh , and the docker-compose up?

This is the way to go, I should add some doc about docker machine maybe :/

**Comment by cimi** [comment]
I have the same problem on Ubuntu Precise (12.04 LTS). No `docker-machine`, not running Docker through VBox (although there is a VBox running on the system).

I had to build the piwik Docker image locally:

```
➜  docker-piwik git:(master) ✗ docker build -t piwik .
```

Then tried to run `docker-compose`:

```
➜  docker-piwik git:(master) ✗ docker-compose up -d
dockerpiwik_db_1 is up-to-date
Starting dockerpiwik_app_1
ERROR: Cannot start container fe2787dccc13c2646116379e0cdf224375b19834ee6d0c4b7afdaeae7af0f30c: [8] System error: not a directory
```

Here are my version numbers:

```
➜  docker-piwik git:(master) ✗ uname -a
Linux uf8bc12856564545249ca 3.13.0-74-generic #118~precise1-Ubuntu SMP Fri Dec 18 10:38:55 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

➜  docker-piwik git:(master) ✗ docker -v
Docker version 1.9.1, build a34a1d5

➜  docker-piwik git:(master) ✗ docker-compose -v
docker-compose version 1.5.2, build 7240ff3
```

**Comment by pierreozoux** [comment]
docker-compose is no longer supported in this repo.
If you have bugs in compose, thanks to open an issue here:
https://github.com/indiehosters/piwik
